### ISSUE TITLE
Unable to Access Franklin Sharepoint

### ISSUE THREAD

**Issue by kyleerobison** [hlxsites/wgf-pga-tour#2]
Looks like the following are unable to access Franklin - is there any insight into this?
Currently I'm aware that it doesn't work for the following:
garystover@pgatourhq.com
vinceshannon@pgatourhq.com
willdelorenzo@pgatourhq.com
kyleerobison@pgatourhq.com

![image](https://user-images.githubusercontent.com/124196383/230952730-84eacd42-c87d-489b-8603-dc13dba30ce4.png)

**Comment by tripodsan** [comment]
should work now.
